import { extractPdfRows } from './pdfTableExtractor';
import type { RawTransaction, ParserInput } from '../registry';

export async function parseBoiPdf(input: ParserInput): Promise<RawTransaction[]> {
  const { rows } = await extractPdfRows(input.buffer, input.password);
  const transactions: RawTransaction[] = [];

  const datePattern = /^(\d{2}[-/.]\d{2}[-/.]\d{4})/;

  let debitHeaderX = 470;
  let creditHeaderX = 570;

  for (const row of rows) {
    const text = row.lineText;

    // Detect column header X coordinates if available
    for (const item of row.items) {
      const s = item.text.trim();
      if (/^Debits$/i.test(s) || /^Withdrawal/i.test(s)) {
        debitHeaderX = item.x;
      } else if (/^Credits$/i.test(s) || /^Deposit/i.test(s)) {
        creditHeaderX = item.x;
      }
    }

    // Skip noise/header/footer rows
    if (
      text.startsWith('DATE :') ||
      text.startsWith('Statement of Account') ||
      text.startsWith('Total C/F:') ||
      text.startsWith('B/F') ||
      text.startsWith('PAGE :') ||
      text.startsWith('PAGE:') ||
      text.startsWith('A/C No') ||
      text.startsWith('BANK OF INDIA') ||
      text.startsWith('M/S.') ||
      text.startsWith('Deposit Insurance') ||
      text.startsWith('Generated at') ||
      text.startsWith('Generated By') ||
      text.startsWith('Generation Time') ||
      text.startsWith('-----') ||
      text.startsWith('Date Description') ||
      text.includes('RELATIONSHIP BEYOND BANKING') ||
      text.includes('Toll free no.') ||
      text.includes('MAKE USE OF RTGS/NEFT')
    ) {
      continue;
    }

    if (datePattern.test(text)) {
      const match = text.match(/^(\d{2}[-/.]\d{2}[-/.]\d{4})\s+(.*)/);
      if (!match) continue;

      const dateStr = match[1];
      const remainder = match[2] || '';

      // Find amount items matching numbers with decimals (e.g. 15,000.00 or 4,27,86,261.89)
      const amountItems = row.items.filter(i => /[\d,]+\.\d{2}/.test(i.text.trim()));

      let description = remainder;
      let refNo = '';
      let debit: number | undefined;
      let credit: number | undefined;
      let balance: number | undefined;

      const midpointX = (debitHeaderX + creditHeaderX) / 2;

      if (amountItems.length >= 2) {
        // Last item is running balance
        const balanceItem = amountItems[amountItems.length - 1];
        const txnItem = amountItems[amountItems.length - 2];

        if (balanceItem) {
          balance = parseFloat(balanceItem.text.replace(/,/g, '').trim());
        }

        if (txnItem) {
          const amtVal = parseFloat(txnItem.text.replace(/,/g, '').trim());
          const itemX = txnItem.x;
          if (itemX >= midpointX || text.includes('CREDIT')) {
            credit = amtVal;
          } else {
            debit = amtVal;
          }
        }

        // Instrument No. check (if present between description and amount)
        const descItems = row.items.filter(i => i.x < (txnItem ? txnItem.x : 500));
        let fullDesc = descItems.map(i => i.text.trim()).join(' ').replace(/^(\d{2}[-/.]\d{2}[-/.]\d{4})\s*/, '').trim();

        const descParts = fullDesc.split(/\s+/);
        const lastPart = descParts[descParts.length - 1] || '';
        if (/^\d{5,8}$/.test(lastPart)) {
          refNo = lastPart;
          description = descParts.slice(0, descParts.length - 1).join(' ');
        } else {
          description = fullDesc;
        }
      } else if (amountItems.length === 1) {
        const balanceItem = amountItems[0];
        if (balanceItem) {
          balance = parseFloat(balanceItem.text.replace(/,/g, '').trim());
        }
        const descItems = row.items.filter(i => i.x < (balanceItem ? balanceItem.x : 600));
        description = descItems.map(i => i.text.trim()).join(' ').replace(/^(\d{2}[-/.]\d{2}[-/.]\d{4})\s*/, '').trim();
      }

      transactions.push({
        date: dateStr,
        narration: description,
        refNo,
        debit,
        credit,
        balance
      });
    } else if (transactions.length > 0) {
      // Append multi-line narration continuation
      const last = transactions[transactions.length - 1];
      if (last && text.length > 0) {
        last.narration += ' ' + text;
      }
    }
  }

  return transactions;
}
