import { defineEventHandler, createError } from 'h3';
import mongoose from 'mongoose';
import Ledger from '../../../models/Ledger';
import { requireAuthSession } from '../../../utils/auth';
import { getSql, connectPostgres } from '../../../utils/pg.config';
import { isPeriodLocked } from '../../../utils/accounting/period-lock.service';

export default defineEventHandler(async (event) => {
  try {
    const session = await requireAuthSession(event);
    const firmIdStr = String(session.firm_id);
    const firmIdObj = new mongoose.Types.ObjectId(firmIdStr);

    const voucherGroupId = event.context.params?.voucherGroupId;
    if (!voucherGroupId || !voucherGroupId.trim()) {
      throw createError({ statusCode: 400, statusMessage: 'Voucher Group ID is required' });
    }

    const entries = await Ledger.find({
      $or: [{ firmId: firmIdObj }, { firm_id: firmIdObj }],
      voucherGroupId: voucherGroupId.trim()
    }).lean();

    if (!entries || entries.length === 0) {
      throw createError({ statusCode: 404, statusMessage: `Voucher "${voucherGroupId}" not found in General Ledger` });
    }

    const firstEntry = entries[0]!;
    const vtype = (firstEntry.voucherType || 'JOURNAL').toUpperCase();
    const vdate = firstEntry.transactionDate;
    const narration = firstEntry.narration || '';
    const voucherNo = firstEntry.voucherNo || voucherGroupId;

    let isEditable = true;
    let notEditableReason = '';

    // Guard 1: Commercial Bills
    if (['BILL', 'SALE', 'PURCHASE'].includes(String(firstEntry.refType).toUpperCase())) {
      isEditable = false;
      notEditableReason = 'This voucher was generated by a Commercial Bill. Please modify or cancel the bill in the Invoicing/Bills module.';
    }

    // Guard 2: Period Lock
    const locked = await isPeriodLocked(firmIdObj, vdate);
    if (locked) {
      isEditable = false;
      notEditableReason = `This voucher belongs to a locked financial period (${vdate}).`;
    }

    // Guard 3: PostgreSQL Labor Settlement
    let linkedAdvances: any[] = [];
    try {
      let sql = getSql();
      if (!sql) sql = await connectPostgres();
      if (sql) {
        const [activeSettlement] = await sql`
          SELECT id, period_id FROM labor_settlements WHERE ledger_voucher_group_id = ${voucherGroupId} LIMIT 1
        `;
        if (activeSettlement) {
          isEditable = false;
          notEditableReason = 'This voucher is linked to an active Labor Settlement. Please use "Reopen / Unsettle Period" in the Labor module to safely edit or cancel it.';
        }

        linkedAdvances = await sql`
          SELECT id, period_id, amount FROM labor_advances WHERE ledger_voucher_group_id = ${voucherGroupId}
        `;
      }
    } catch (pgErr: any) {
      console.warn('Postgres labor check notice:', pgErr?.message || pgErr);
    }

    // Reconstruct single-entry or double-entry view
    let mainAccount = '';
    const formEntries: any[] = [];

    if (vtype === 'PAYMENT') {
      // Find main paid-from bank/cash leg (the credit leg on Bank/Cash)
      const bankLeg = entries.find(e => 
        e.bankAccountId || 
        ['BANK', 'CASH'].includes((e.accountType || '').toUpperCase()) ||
        (e.creditAmount > 0 && entries.filter(x => x.creditAmount > 0).length === 1)
      ) || entries.find(e => e.creditAmount > 0);

      if (bankLeg) {
        mainAccount = bankLeg.bankAccountId ? String(bankLeg.bankAccountId) : bankLeg.accountHead;
      }

      for (const e of entries) {
        if (e === bankLeg) continue;
        const isDeduction = (e.creditAmount || 0) > 0;
        const amount = isDeduction ? -(e.creditAmount || 0) : (e.debitAmount || 0);

        let matchedPeriodId = '';
        if (linkedAdvances && linkedAdvances.length > 0) {
          const adv = linkedAdvances.find(a => Math.abs(Number(a.amount) - Math.abs(amount)) < 0.01) || linkedAdvances[0];
          if (adv) matchedPeriodId = adv.period_id;
        }

        formEntries.push({
          accountHead: e.accountHead,
          accountType: e.accountType,
          amount,
          isDeduction,
          laborPeriodId: matchedPeriodId
        });
      }
    } else if (vtype === 'RECEIPT') {
      // Find main deposit-to bank/cash leg (the debit leg on Bank/Cash)
      const bankLeg = entries.find(e => 
        e.bankAccountId || 
        ['BANK', 'CASH'].includes((e.accountType || '').toUpperCase()) ||
        (e.debitAmount > 0 && entries.filter(x => x.debitAmount > 0).length === 1)
      ) || entries.find(e => e.debitAmount > 0);

      if (bankLeg) {
        mainAccount = bankLeg.bankAccountId ? String(bankLeg.bankAccountId) : bankLeg.accountHead;
      }

      for (const e of entries) {
        if (e === bankLeg) continue;
        const isDeduction = (e.debitAmount || 0) > 0;
        const amount = isDeduction ? -(e.debitAmount || 0) : (e.creditAmount || 0);

        formEntries.push({
          accountHead: e.accountHead,
          accountType: e.accountType,
          amount,
          isDeduction,
          laborPeriodId: ''
        });
      }
    } else {
      // JOURNAL or CONTRA
      for (const e of entries) {
        formEntries.push({
          accountHead: e.accountHead,
          accountType: e.accountType,
          debitAmount: e.debitAmount || 0,
          creditAmount: e.creditAmount || 0,
          amount: e.debitAmount ? e.debitAmount : -(e.creditAmount || 0),
          isDeduction: false,
          laborPeriodId: ''
        });
      }
    }

    return {
      success: true,
      data: {
        voucherGroupId,
        voucherNo,
        vtype,
        vdate,
        narration,
        mainAccount,
        entries: formEntries.length > 0 ? formEntries : [{ accountHead: '', amount: 0, isDeduction: false, laborPeriodId: '' }],
        isEditable,
        notEditableReason,
        canDelete: isEditable,
        notDeletableReason: notEditableReason
      }
    };
  } catch (err: any) {
    throw createError({
      statusCode: err.statusCode || 500,
      statusMessage: err.statusMessage || err.message || 'Failed to fetch voucher details'
    });
  }
});
