import { defineEventHandler, createError } from 'h3';
import mongoose from 'mongoose';
import Ledger from '../../../models/Ledger';
import { enforcePeriodLock } from '../../../utils/accounting/period-lock.service';
import { requireAuthSession } from '../../../utils/auth';
import { getSql, connectPostgres } from '../../../utils/pg.config';

export default defineEventHandler(async (event) => {
  try {
    const session = await requireAuthSession(event);
    const firmIdStr = String(session.firm_id);
    const firmIdObj = new mongoose.Types.ObjectId(firmIdStr);

    const voucherGroupId = event.context.params?.voucherGroupId;
    if (!voucherGroupId || !voucherGroupId.trim()) {
      throw createError({ statusCode: 400, statusMessage: 'Voucher Group ID is required' });
    }

    // 1. Locate existing entries for this voucher
    const entries = await Ledger.find({
      $or: [{ firmId: firmIdObj }, { firm_id: firmIdObj }],
      voucherGroupId: voucherGroupId.trim()
    }).lean();

    if (!entries || entries.length === 0) {
      throw createError({ statusCode: 404, statusMessage: `Voucher "${voucherGroupId}" not found in General Ledger` });
    }

    const firstEntry = entries[0]!;

    // 2. Period Lock Guard
    if (firstEntry.transactionDate) {
      await enforcePeriodLock(firmIdObj, firstEntry.transactionDate);
    }

    // 3. Subsystem integrity guards
    if (['BILL', 'SALE', 'PURCHASE'].includes(String(firstEntry.refType).toUpperCase())) {
      throw createError({
        statusCode: 400,
        statusMessage: 'This voucher was generated by a Commercial Bill. Please cancel the bill in the Bills module to preserve inventory and GST integrity.'
      });
    }

    // 4. Check if linked to an active PostgreSQL labor settlement
    try {
      let sql = getSql();
      if (!sql) sql = await connectPostgres();
      if (sql) {
        const [activeSettlement] = await sql`
          SELECT id, period_id FROM labor_settlements WHERE ledger_voucher_group_id = ${voucherGroupId} LIMIT 1
        `;
        if (activeSettlement) {
          throw createError({
            statusCode: 400,
            statusMessage: 'This voucher is currently linked to an active Labor Settlement. Please use "Reopen / Unsettle Period" in the Labor module to safely cancel it.'
          });
        }
      }
    } catch (pgErr: any) {
      if (pgErr.statusCode) throw pgErr;
    }

    // 5. Delete voucher legs atomically
    const mongoSession = await mongoose.startSession();
    mongoSession.startTransaction();
    try {
      await Ledger.deleteMany(
        {
          $or: [{ firmId: firmIdObj }, { firm_id: firmIdObj }],
          voucherGroupId: voucherGroupId.trim()
        },
        { session: mongoSession }
      );

      await mongoSession.commitTransaction();
    } catch (dbErr) {
      await mongoSession.abortTransaction();
      throw dbErr;
    } finally {
      mongoSession.endSession();
    }

    return {
      success: true,
      message: `Voucher ${voucherGroupId} (${entries[0]?.voucherNo || voucherGroupId}) was deleted successfully.`,
      deletedCount: entries.length
    };
  } catch (err: any) {
    console.error('Delete voucher error:', err);
    throw createError({
      statusCode: err.statusCode || 500,
      statusMessage: err.statusMessage || err.message || 'Failed to delete voucher'
    });
  }
});
